### ISSUE TITLE
How do I user dockercloud-haproxy in docker swarm mode (Docker Engine v1.12.0)?

### ISSUE THREAD

**Issue by qinains** [docker/dockercloud-haproxy#100]
Environment:
Docker Engine v1.12.0
3 nodes in the swarm cluster: 1 manager,2 workers

Then I created 2 services:

`docker service create --replicas 3 --name nginx --container-label com.docker.compose.service="nginx" --container-label com.docker.compose.project="myproject" --env VIRTUAL_HOST="www.example.com" --publish 30001:80 --publish 30002:433 --update-delay 10s --update-parallelism 2 nginx:alpine`

`docker service create --name lb --mode global --container-label com.docker.compose.service="lb" --container-label com.docker.compose.project="myproject" --env ADDITIONAL_SERVICES=myproject:nginx --env STATS_AUTH="auth:auth" --mount type=bind,src=/var/run/docker.sock,dst=/var/run/docker.sock --publish 80:80 --publish 443:433 --publish 1936:1936 dockercloud/haproxy:1.5.3`

When I visited http://www.example.com , it work. But some nodes it cannot arrive. Example, it can hit the node1 and node3, the node2 never be hit.
 Why? 
Can it support `labels.get("com.docker.swarm.service.name", "")` in the file dockercloud-haproxy/haproxy/helper/new_link_helper.py ?

**Comment by mrlesmithjr** [comment]
This seems to be related as well?
[https://github.com/jwilder/docker-gen/issues/207](url)

No luck for me either.

**Comment by pascalandy** [comment]
Surprise to see more traction on this topics. I'm on the same boat as you two. 
https://github.com/jwilder/nginx-proxy/issues/520#issuecomment-241280818

**Comment by tifayuki** [comment]
@qinains 

I have opened a PR to support swarm mode. (https://github.com/docker/dockercloud-haproxy/pull/118).

Any feedback is welcomed.

**Comment by pablolibo** [comment]
mmmm, dockercloud/haproxy:1.5.3 always run in leader node, not in conventional node, because it doesn't work.

the documentation about swarm and dockercloud said: 

````
example of docker swarm mode support

docker network create -d overlay proxy
docker service create --name haproxy --network proxy --mount target=/var/run/docker.sock,source=/var/run/docker.sock,type=bind -p 80:80 --constraint "node.role == manager" dockercloud/haproxy
docker service create -e SERVICE_PORTS="80" --name app --network proxy --constraint "node.role != manager" dockercloud/hello-world
docker service scale app=2
docker service update --env-add VIRTUAL_HOST=web.org app
````

When you use " --constraint "node.role != manager"", the container only run in leader node.

**Comment by tifayuki** [comment]
@pablolibo 

The support of docker swarm mode starts from version 1.6.0, you should use a newer version instead of 1.5.3, which only supports the classic swarm as I remembered.

Haproxy container does requires to run on a manager node, not limited only to leader. The linked application can be run on all kinds of nodes: workers and managers(including leader).

It could be like when you set "node.role == manager", the node chosen to run the container happens to be the leader. You can find more about swarm scheduler here: https://docs.docker.com/v1.10/swarm/scheduler/filter/

**Comment by santhoshkumarhirekerur** [comment]
I followed article. Its working for me.  
https://medium.com/@nirgn/load-balancing-applications-with-haproxy-and-docker-d719b7c5b231
