### ISSUE TITLE
How to test VIRTUAL_HOST locally?

### ISSUE THREAD

**Issue by sunshineo** [docker/dockercloud-haproxy#104]
Hello,

I'm trying to test locally for the VIRTUAL_HOST settings. What I have to do now is edit my /etc/hosts file and add entry like
127.0.0.1 www.mydomain.com

So that I can enter www.mydomain.com in the browser and hit my local haproxy which will route to the VIRTUAL_HOST as the traffic is from www.mydomain.com

Is there an easier way to do this? Is there a way to do this without edit /etc/hosts ? I'm assuming VIRTUAL_HOST is looking at the request url or something. Is there a way to make haproxy belive my request is coming from a particular domain? Can POSTMAN do this with some header?

Thank you very much!

**Comment by tifayuki** [comment]
@sunshineo 

you can use curl to test VIRTUAL_HOST, like this:
`curl --resolve  www.mydomain.com:80:127.0.0.1  www.mydomain.com`

**Comment by sunshineo** [comment]
Thank you @tifayuki
