### ISSUE TITLE
 'appsession' is not supported anymore ...

### ISSUE THREAD

**Issue by damshenas** [docker/dockercloud-haproxy#105]
According to https://github.com/docker/dockercloud-haproxy/blob/master/README.md 

> ### Settings in linked application services
> 
> | Environment Variable | Description |
> | :-: | :-- |
> | APPSESSION | sticky session option, possible value `JSESSIONID len 52 timeout 3h`. See:> [HAProxy:appsession](http://cbonte.github.io/haproxy-dconv/configuration-1.5.html#4-appsession) |

I should be able to use APPSESSION but when I use it I get the following logs. Although the container keep running, the haproxy is not functional ...

> [test-haproxy-1]2016-09-06T03:10:02.710274429Z INFO:haproxy:dockercloud/haproxy 1.5.3 has access to the Docker Cloud API - will reload list of backends in real-time 
> [test-haproxy-1]2016-09-06T03:10:02.710404344Z INFO:haproxy:dockercloud/haproxy PID: 5 
> [test-haproxy-1]2016-09-06T03:10:03.818713615Z INFO:haproxy:==========BEGIN========== 
> [test-haproxy-1]2016-09-06T03:10:03.818870885Z INFO:haproxy:Websocket open 
> [test-haproxy-1]2016-09-06T03:10:05.551222104Z INFO:haproxy:Linked service
> .
> .
> .
> [test-haproxy-2]2016-09-06T03:10:05.700802671Z frontend default_port_80 
> [test-haproxy-2]2016-09-06T03:10:05.700805013Z   bind :80 
> [test-haproxy-2]2016-09-06T03:10:05.700807399Z   reqadd X-Forwarded-Proto:\ http 
> [test-haproxy-2]2016-09-06T03:10:05.700809868Z   maxconn 4096 
> [test-haproxy-2]2016-09-06T03:10:05.700812264Z   default_backend default_service 
> [test-haproxy-2]2016-09-06T03:10:05.700814742Z backend default_service 
> [test-haproxy-2]2016-09-06T03:10:05.700817305Z   appsession JSESSIONID len 52 timeout 3h 
> [test-haproxy-2]2016-09-06T03:10:05.700820003Z   server TEST_WEB_1 10.7.0.18:3009 cookie TEST_WEB_1 check inter 2000 rise 2 fall 3 
> [test-haproxy-2]2016-09-06T03:10:05.701766835Z INFO:haproxy:Launching HAProxy 
> [test-haproxy-2]2016-09-06T03:10:05.704390434Z INFO:haproxy:HAProxy has been launched(PID: 12) 
> [test-haproxy-2]2016-09-06T03:10:05.704487627Z INFO:haproxy:===========END=========== 
> [test-haproxy-2]2016-09-06T03:10:05.712053875Z [ALERT] 249/031005 (12) : parsing [/haproxy.cfg:41] : 'appsession' is not supported anymore, please check the documentation. 
> [test-haproxy-2]2016-09-06T03:10:05.712097736Z [ALERT] 249/031005 (12) : Error(s) found in configuration file : /haproxy.cfg 
> [test-haproxy-2]2016-09-06T03:10:05.712179041Z [ALERT] 249/031005 (12) : Fatal errors found in configuration. 

Just in case it helps:

> test-haproxy:
>   deployment_strategy: every_node
>   image: 'dockercloud/haproxy:latest'
>   links:
>     - test-web
>   ports:
>     - '80'
>   roles:
>     - global
> test-web:
>   environment:
>     - APPSESSION=JSESSIONID len 52 timeout 3h
>   image: 'my image that listens on 3009'
>   ports:
>     - '3009'

**Comment by NicoTexas** [comment]
Just tested and got the same result with latest version.

**Comment by Franklin89** [comment]
Same here... 
@tifayuki any updates on this?

**Comment by tifayuki** [comment]
I have removed appsession in staging branch and create a new issue to support stick-table: https://github.com/docker/dockercloud-haproxy/issues/191
Close this one.
