### ISSUE TITLE
HAProxy redirects everytime to https

### ISSUE THREAD

**Issue by buehler** [docker/dockercloud-haproxy#108]
Hey guys

I've got a quick question:
My setup has a container that is linked to the proxy with `FORCE_SSL=true`, a valid cert and the corresponding VIRTUAL_HOST.

Now a second container is linked to the proxy with only `VIRTUAL_HOST=http://...` and whenever I connect to this url, I'll be redirected to https. What am I doing wrong?

**Comment by LoungeFlyZ** [comment]
Is your FORCE_SSL=true on the proxy container? If so then it is working as designed.  You should put the FORCE_SSL on the service container if you want to control it service by service.

**Comment by buehler** [comment]
Well I had FORCE_SSL set to "empty". And then I had it removed at all.
But since I have a certificate, I now use the certificate, so it's not to worry anymore ;-)

Maybe there was a misconfiguration or some HSTS or whatev

Cheers!
