### ISSUE TITLE
ipv4 ipv6 question

### ISSUE THREAD

**Issue by kersten** [docker/dockercloud-haproxy#109]
Hello,

I need your help. I set up three stacks with three webapps. For these stacks I configured one proxy. The proxy listens now to only the ipv6 address and not on ipv4.

nmap output:

```
Nmap scan report for 2a01:...
Host is up (0.056s latency).
Not shown: 998 closed ports
PORT    STATE SERVICE
80/tcp  open  http
443/tcp open  https

Nmap scan report for 136....
Host is up (0.088s latency).
All 1000 scanned ports on 136... are closed
```

Is there an easy way of setting both interfaces to listen on?

Another question for me is: The proxy now listens on ipv6 but internally it redirects to ipv4 address of the container. When I do a `curl -6 webbapp1.com` I do not get a response, it stays in connection state or something like this. I have to force (ctrl+c) quit curl.

Can somebody help me here, or give me a hint what I do wrong?

**Comment by kersten** [comment]
Strange, now if added following options to ```/etc/dockercloud/agent/dockercloud-agent.conf```

```
"DockerOpts":"--ipv6 --iptables --ip-masq"
```

After a restart of cloud agent nmap now says following:

```
Starting Nmap 7.12 ( https://nmap.org ) at 2016-09-15 15:04 CEST
Nmap scan report for 2a01:...
Host is up (0.043s latency).
Not shown: 998 closed ports
PORT    STATE SERVICE
80/tcp  open  http
443/tcp open  https

Starting Nmap 7.12 ( https://nmap.org ) at 2016-09-15 15:04 CEST
Nmap scan report for 136....
Host is up (0.048s latency).
Not shown: 999 closed ports
PORT   STATE SERVICE
80/tcp open  http

Nmap done: 1 IP address (1 host up) scanned in 2.07 seconds
```

**Comment by kersten** [comment]
Update: After adding SSL certificate to haproxy config, the 443 now listen on the ipv4 interface too. This is kind of strange to me, why is the container listen always on ipv6 on https?

But routing with ipv6 is still not possible.

**Comment by tifayuki** [comment]
@kersten 

I am not sure how to config both ipv4 and ipv6. 
As far as I know, dockercloud uses `weave` for overlay network, and it onlys configures IPV4 address (see: https://github.com/docker/dockercloud-network-daemon/blob/master/run.sh#L74). I think it is the reason that you cannot route to ipv6 address.

If you have further question about the networking in Docker Cloud, please contact the support team.
