### ISSUE TITLE
Haproxy stops working for no reason around once every day

### ISSUE THREAD

**Issue by sunshineo** [docker/dockercloud-haproxy#110]
It is serving couple sites. Almost no traffic. Around once a day, it just stopped working. The service shows running, the container shows running, but the endpoint does not work. It just shows a connection error. There is no log message indicate what is happening at all. After re-deploy the service, it came back up online.
I'm not sure if the problem lies in this docker image or docker cloud's network infrastructure.

**Comment by PuKoren** [comment]
Had no issue with this image but a lot with Docker Cloud for networking

Is your LB and your backends located in the same datacenter?

When you restart a service, the LB refreshes its config so I guess it is the route/ip that is changing behind the scene but maybe not noticed by weave - or you have a bug in the service and it stops receiving connections after some time for some reason

Maybe try to compare the config before and after a restart, and see what changed - if nothing changed, maybe its your service that have a bug

**Comment by sunshineo** [comment]
@PuKoren Yes. Now I found some logs:
I see a lot of things like
```
server CRAIGSMENU_PRERENDER_WWW_1 10.7.0.22:80 check inter 2000 rise 2 fall 3
```
Then it fails.
![haproxy](https://cloud.githubusercontent.com/assets/1072766/18681330/7494b90a-7f1c-11e6-8262-8bae2463c028.jpg)

**Comment by sunshineo** [comment]
Happening again.

2016-09-20T21:10:27.113492860Z INFO:haproxy:HAProxy has been reloaded(PID: 16)
2016-09-20T21:10:27.113805024Z INFO:haproxy:===========END===========
2016-09-20T21:10:29.515384849Z INFO:haproxy:HAProxy(PID:15) has been terminated

**Comment by tifayuki** [comment]
@sunshineo 
It is supposed to be like that. when the haproxy is reloaded, a new process (PID: 16) is spawned, and the old one is terminated(PID:15).

**Comment by sunshineo** [comment]
@tifayuki I got that one. But this project is really no longer working for me. It dies once every day for me for no reason with no logs to support debugging. I'm leaving.
