### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by dev-lusaja** [docker/dockercloud-haproxy#114]
Hi,
I need create a virtual host "dashboard-example.com" and that internally the HAproxy forward to dashboard-example.com:8080
this is posible ??

**Comment by tifayuki** [comment]
Do you mean`user -----dashboard-example.com---->haproxy-------->your_linked_container:8080`?

If yes, you only need to make sure that your linked container exposes port 8080.
If no, I don't think it is possible. You may need some redirect instructions of haproxy and configure it through EXTRA_XXX_SETTINGS environment variable.
