### ISSUE TITLE
Link to a particular service kills haproxy and no log message for debug.

### ISSUE THREAD

**Issue by sunshineo** [docker/dockercloud-haproxy#116]
Hello, I've been complaining about haproxy dies on me before. Now I think I have a little more information. It is due to a particular service that I link to. The second I link to it, haproxy dies without any log.
The service is a prerender service I started using https://github.com/prerender/prerender
Here is the final log screenshot
![dies](https://cloud.githubusercontent.com/assets/1072766/18807185/9e0138e6-81f5-11e6-9d6f-3270ec4505a3.jpg)

**Comment by tifayuki** [comment]
@sunshineo 
Do you have a stackfile which I can use to reproduce the issue?

Thank you

**Comment by sunshineo** [comment]
I'll look into that. But this thing may not reproduce.

**Comment by tifayuki** [comment]
@sunshineo 
There are two processes running in `dockercloud/haproxy` container:
1. the script, which generates the configure file and invokes haproxy
2. the haproxy

Both the two processes are backend agnostic:
The script only reads environment variable from the linked services and use the information to generate the configuration file that feeds the haproxy. 
The haproxy is responsible to forward packet to the related ports.

So in theory, `dockercloud/haproxy` should always work regardless what services it is linked to. If the script stops unexpectedly, it is a bug of this repo. If the haproxy terminates unexpectedly, it could be a bug of the haproxy itself.

When you see this error again, can you exec into the haproxy container and run `ps aufx` to see if the haproxy is running?

Also, in staging branch, I have updated the code to monitor haproxy. If the haproxy process quits unexpectedly, the script will restart it. I think this can help you mitigate the issue.

Thank you.
