### ISSUE TITLE
Issue with couchbase container: 504 Gateway Time-out or 502 Bad Gateway

### ISSUE THREAD

**Issue by jplu** [docker/dockercloud-haproxy#124]
Hello,

I have some issues to access to a couchbase container via dockercloud-haproxy. After doing these two simple command line:

```
docker run -d --expose 8091 --name couchbase couchbase
docker run -d --link couchbase:couchbase -p 8091:80 dockercloud/haproxy
```

Everytime I try to access to the couchbase's web interface on [http://localhost:8091/index.html]() I get two random errors, either ```504 Gateway Time-out``` or ```502 Bad Gateway```.

Is there anything else I have to configure or is it really a bug?

Thanks in advance for any help.

**Comment by tifayuki** [comment]
@jplu 
If you look into the couchbase image, there are more than one ports exposed in that images. As a result, all those ports are load balanced in haproxy which could return you an error.

You can exclude those ports and haproxy should work as expected. Here is an example: https://github.com/docker/dockercloud-haproxy#my-webapp-container-exposes-port-80-and-database-ports-80838086-and-i-want-the-proxy-to-listen-in-port-80-without-my-database-ports-added-to-haproxy

**Comment by jplu** [comment]
Hello @tifayuki 

I do have the same issue even when I exclude the other ports. Here what I have done:

```
docker run -d -e EXCLUDE_PORTS=8092,8093,8094,11207,11210,11211,18091,18092,18093 --expose 8091 --expose 8092 --expose 8093 --expose 8094 --expose 11207 --expose 11210 --expose 11211 --expose 18091 --expose 18092 --expose 18093 --name couchbase couchbase
docker run -d --link couchbase:couchbase -p 8091:80 dockercloud/haproxy
```

Even by doing this I get the random gateway errors.
