### ISSUE TITLE
Error: EXDEV: cross-device link not permitted

### ISSUE THREAD

**Issue by keyscores** [docker/dockercloud-haproxy#127]
I'm getting this error in docker cloud, but not in quay.io . Quay builds perfectly. I don't know what a cross-device link is, in docker context.

The full error is:
Error: EXDEV: cross-device link not permitted, rename '/opt/meteor/dist/bundle' -> '/opt/meteor/dist/bundle-garbage-14tplr2'

**Comment by pchico83** [comment]
Could you share the repo name?

**Comment by keyscores** [comment]
It's this image that causes failure when building: jshimko/meteor-launchpad:latest

**Comment by zachariahtimothy** [comment]
@keyscores from what I can understand it has to do with the AUFS file system. That being said, I have no idea how to fix or change it. Would LOVE to learn the fix though!

**Comment by tifayuki** [comment]
@pchico83 Any update on the issue?

PS: I don't think this issue is directly related to `dockercloud/haproxy` image, and I would like to close it at the moment.

**Comment by zachariahtimothy** [comment]
@tifayuki Just FYI, you are totally correct that the problem is not related directly to dockercloud/haproxy . I am not using it at all.

**Comment by keyscores** [comment]
@zachariahtimothy I have been docker cloud, but instead of using docker's infrastructure I choose 'build on own servers', or whatever that option is.  Seems like docker's servers have just too many issues. 

The error goes away using the latest  jshimko/meteor-launchpad:latest .

**Comment by zachariahtimothy** [comment]
@keyscores Interesting to hear your response, I am using jshimko/meteor-launchpad:latest and still get the problem! Now I am totally stumped. Did you have to do anything different with your docker daemon or config to get it working?
