### ISSUE TITLE
HTTP and WebSocket on the same underlying container?

### ISSUE THREAD

**Issue by thebigredgeek** [docker/dockercloud-haproxy#128]
I am working on a new GraphQL API with Subscriptions (WS or WebSockets) for a new product offering at my company.  Each server instance will provide a traditional REST (POST only) API for GraphQL, as well as a WS based subscription stream that GraphQL will write to.  Thus, the server will expose two different ports: 80 for REST and 81 for WS.  The websockets need to be load balanced with sticky sessions (source-based balancing), whereas the REST port should probably be load balanced via round-robbin to keep load predictable.  Is there a way to accomplish this with a single LB instance on docker cloud?  If not, is there a way to use two different LB instances and bind one of them with round robin to the server's port 80 (REST) and the other with source to the server's port 81 (WS)?

**Comment by thebigredgeek** [comment]
bump

**Comment by tifayuki** [comment]
@thebigredgeek 
you can try something like `-e BALANCE=source  -e EXTRA_FRONTEND_SETTINGS_80="balance roundrobin"` in the haproxy container.

This will set the default load balancing strategy to "tcp source", which applies to the websocket, and set roundrobin to your REST port.
