### ISSUE TITLE
Stats not showing for service at another port that is not 80

### ISSUE THREAD

**Issue by nicolasgaraza** [docker/dockercloud-haproxy#129]
Hi, I'm new to docker and haproxy. Right now I'm doing a simple test to test an application divided in 2 services, Web and View.

Web connects to view using a http client at _http://view:5002_. My docker-compose file is as follows:

    version: '2'
   
    services:
      lbweb:
        image: 'dockercloud/haproxy:latest'
        links:
        - web
        - view
        ports:
        - '80:80'
        - '1936:1936'
        volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        environment:
            EXTRA_GLOBAL_SETTINGS: debug
      web:
        environment:
            ASPNETCORE_ENVIRONMENT: Docker
            VIRTUAL_HOST: "*"
        build: Web/
        expose: 
            - 80
      view:
        environment:
            ASPNETCORE_ENVIRONMENT: Docker 
            VIRTUAL_HOST: view:5002
        build: View/
        expose:
            - 5002 

The application works fine, and if I access to http://localhost:1936/ I can see all the instances of my containers and services, but for some reason no stats are updated for the service **view** 

![haproxy stats](https://cloud.githubusercontent.com/assets/3244621/19972260/30037062-a1c0-11e6-9cb4-6a8325a34a9e.png)

Could you guys help me with this?

**Comment by tifayuki** [comment]
@nicolasgaraza 

No sure, but I think you need to publish the port `5002` in the haproxy container as well.

**Comment by nicolasgaraza** [comment]
Sorry, no luck either. Same result
