### ISSUE TITLE
How do I tell haproxy to exclude ports

### ISSUE THREAD

**Issue by moshhasa** [docker/dockercloud-haproxy#131]
Hi, I am new to docker and haproxy. I have two services running and i want haproxy to route request to either  appA:8001 or appB:8051. when i start haproxy it start additional servers listening on some different ports. i have added and environment variable <b>EXCLUDE_PORTS=5556,7001</b> to haproxy but somehow it still list them in the backend servers.

This is my docker-compose.yml
<pre>
version: '2'
services:
    admje:       
      image: comp.repos/deploy-war:latest
      ports:
        - "8051:8041"
        - "8851:8887"
      environment:
        - ENV_DB_HOST_NAME=host
        - ENV_DB_HOST_PORT=3521
        - ENV_DB_HOST_SID=SOMEID
        - ENV_DEAJAVIEW_CODEBASE=http://localhost:8041/Daeja
        - ENV_HELP_URL=http://localhost:8041/systest_help
        - ENV_DOCSTORE_URL=http://localhost:8044/documentstore/rest/
        - ENV_JMS_NAMING=tcp://localhost:61616
        - ENV_EI_ADDRESS_URI=http://admei:8043/admei-qas-adapter/enterprise/EIPAddressLookup-httpinvoker
        - ENV_EI_BANK_URI=http://adei:8043/adei-adapter/enterprise/EIPBankWizard-httpinvoker
        - ENV_HTTP_PORT=8041
        - ENV_HTTPS_PORT=18041
        - http_proxy=
        - https_proxy=
        - VIRTUAL_HOST=''
      restart: unless-stopped
      networks:
        net:
    admjewls:
      image: comp.repos/deploy-ear-wls:latest
      ports:
        - "8001:8001"
        - "8801:8453"
      environment:
        - docstore.url=http://production:8044/documentstore
        - envNumber=102
        - jndi.datasource=jdbc/DEVDS
        - jndi.jms.naming.url=tcp://production:61616
        - JAVA_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8453
      restart: unless-stopped
      networks:
        net:
      restart: unless-stopped
      networks:
        adm_net:
    haproxy:
      image: 'dockercloud/haproxy'
      ports:
        - "8080:80"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      environment:
        - EXTRA_GLOBAL_SETTINGS="debug"
        - STATS_PORT=1936
        - EXCLUDE_PORTS=5556,7001,8453,8887,9080,9443
      links:
        - admje
        - admjewls
      networks:
        net:    
networks:
   net:
</pre>

and this is my generated haproxy.cfg

<pre>
global
  log '127.0.0.1' local0
  log '127.0.0.1' local1 notice
  log-send-hostname
  maxconn 4096
  pidfile /var/run/haproxy.pid
  user haproxy
  group haproxy
  daemon
  stats socket /var/run/haproxy.stats level admin
  ssl-default-bind-options no-sslv3
  ssl-default-bind-ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES128-SHA:DHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:AES128-GCM-SHA256:AES128-SHA256:AES128-SHA:AES256-GCM-SHA384:AES256-SHA256:AES256-SHA:DHE-DSS-AES128-SHA:DES-CBC3-SHA
  "debug"
defaults
  balance roundrobin
  log global
  mode http
  timeout connect 5000
  timeout client 50000
  timeout server 50000
listen stats
  bind :1936
  mode http
  stats enable
  timeout connect 10s
  timeout client 1m
  timeout server 1m
  stats hide-version
  stats realm Haproxy\ Statistics
  stats uri /
 stats auth "login:login"
frontend port_80
  bind :80
  reqadd X-Forwarded-Proto:\ http
  maxconn 4096
  acl is_websocket hdr(Upgrade) -i WebSocket
  acl host_rule_1 hdr(host) -i ''
  acl host_rule_1_port hdr(host) -i '':80
  use_backend SERVICE_desktop_admje if host_rule_1 or host_rule_1_port
backend default_service
  server desktop_admjewls_1 desktop_admjewls_1:5556 check inter 2000 rise 2 fall 3
  server desktop_admjewls_1 desktop_admjewls_1:7001 check inter 2000 rise 2 fall 3
 <b> server desktop_admjewls_1 desktop_admjewls_1:8001 check inter 2000 rise 2 fall 3</b>
  server desktop_admjewls_1 desktop_admjewls_1:8453 check inter 2000 rise 2 fall 3
backend SERVICE_desktop_admje
  <b>server desktop_admje_1 desktop_admje_1:8041 check inter 2000 rise 2 fall 3</b>
  server desktop_admje_1 desktop_admje_1:8887 check inter 2000 rise 2 fall 3
  server desktop_admje_1 desktop_admje_1:9080 check inter 2000 rise 2 fall 3

</pre>

I only want the two highlighted servers in the backend. what am i doing wrong?

**Comment by tifayuki** [comment]
@moshhasa 
EXCLUDE_PORTS is supposed to be set on your application services, not on the haproxy service.
