### ISSUE TITLE
Question about volumes mapping - docker-compose.yml for Docker on Mac

### ISSUE THREAD

**Issue by itpragmatik** [docker/dockercloud-haproxy#137]
In the readme, example file contains following line. Is this mandatory to have? If yes, then why? If not, just out of curioisty why would have such volume mapping? Thanks!

volumes:
      - /var/run/docker.sock:/var/run/docker.sock

**Comment by tifayuki** [comment]
This image needs to talk to docker daemon (listen to docker event, list services/tasks/containers, etc) to config and dynamic re-config itself. For example, when you scale your app, haproxy will detect the changes and reload itself accordingly.

If you remove the docker sock, the only way haproxy knows the underlying service is from the environment variable. The drawback is 1) it is static 2) not work when docker not adding linked environment variables.

**Comment by tifayuki** [comment]
BTW, instead of mounting docker socket, you can also set "DOCKER_HOST" environment variable

**Comment by itpragmatik** [comment]
@tifayuki  Got it. Thanks. 

So, I can remove this mount and simply add following 2 lines to my haproxy:
```
  environment:
      - DOCKER_HOST
```
Or do I have to add all of the following lines to haproxy:
```
    environment:
      - DOCKER_TLS_VERIFY
      - DOCKER_HOST
      - DOCKER_CERT_PATH
    volumes:
      - $DOCKER_CERT_PATH:$DOCKER_CERT_PATH      
```
Above snippet is taken from the README section (example of docker-compose.yml running on Mac OS)      

I am running Docker for Mac

**Comment by tifayuki** [comment]
It depends. 
If your docker daemon expose a TCP socket, only `DCOKER_HOST` is need.
If your docker daemon uses a TLS socket, you have to set all the env vars.

As for docker for mac, I don't think it expose any TCP or TLS port by default. The easy way is to mount docker unix sock.

**Comment by itpragmatik** [comment]
@tifayuki Thanks. I will keep the mount for docker unix sock for now.
