### ISSUE TITLE
VIRTUAL_HOST for a service at a specific path

### ISSUE THREAD

**Issue by itpragmatik** [docker/dockercloud-haproxy#139]
My objective is haproxy serves all requests for any of the following URLs

https://localhost/myapp/api/object1/action1
https://localhost/myapp/object1/action2
https://localhost/myapp/object2/action11
https://localhost/myapp/api/object10/action99

Essentially I want it to forward any url with https://<any hostname>/myapp prefix to the service that it is load balancing. How should I specify VIRTUAL_HOST parameter? This is what I have for my application service in docker-compose.yml But I am not able to access https://localhost/myapp/greetings - I get 404; not found
```
    environment:
      - JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,address=5005,server=y,suspend=n
      - EXCLUDE_PORTS=5005,9091
      - VIRTUAL_HOST=https://*/myapp/*
```
Following are last few lines of logs for my haproxy
```
frontend port_443
  bind :443 ssl crt /certs/
  reqadd X-Forwarded-Proto:\ https
  maxconn 4096
  acl is_websocket hdr(Upgrade) -i WebSocket
  acl host_rule_1 hdr_reg(host) -i ^.*$
  acl host_rule_1_port hdr_reg(host) -i ^.*:443$
  acl path_rule_1 path_reg -i ^/myapp/.*$
  use_backend SERVICE_docker_app if path_rule_1 host_rule_1 or path_rule_1 host_rule_1_port
backend SERVICE_docker_app
  server docker_app_1 docker_app_1:8040 check inter 2000 rise 2 fall 3
INFO:haproxy:Launching HAProxy
INFO:haproxy:HAProxy has been launched(PID: 13)
INFO:haproxy:===========END===========
```

**Comment by tifayuki** [comment]
If you get a 4xx error, that is usually returned by your app. If the haproxy is not configured correctly  , it will return a 503 error.

**Comment by itpragmatik** [comment]
Got it. Thanks!
