### ISSUE TITLE
Help!!! ADDITIONAL_BACKENDS

### ISSUE THREAD

**Issue by pragmaeduard** [docker/dockercloud-haproxy#145]
I want to insert additional backends using environment variable, I follow yours directions but it doesn't work. I use  EXTRA_FRONTEND_SETTINGS_XX and works good but ADDITIONAL_BACKENDS don't.

```
INFO:haproxy:Launching HAProxy
INFO:haproxy:HAProxy has been launched(PID: 18)
INFO:haproxy:===========END===========
[ALERT] 344/093241 (18) : Proxy 'default_port_80': unable to find required use_backend: 'is_dev'.
[ALERT] 344/093241 (18) : Fatal errors found in configuration.
```
I tried to do this: 
 ```
 -e ADDITIONAL_BACKENDS='backend is_dev, cookie SERVERID insert nocache indirect, option httpchk HEAD /404.html HTTP/1.0, option httpclose, option forwardfor'
```
Please help me see that I'm doing wrong

Thanks in advance

**Comment by tifayuki** [comment]
can you try
`-e EXTRA_FRONTEND_SETTINGS_80="default_backend EXWEB" -e "ADDITIONAL_BACKEND_EXWEB=server srv 192.168.203.71:8080 check inter 2000 rise 2 fall 3"`

I think `use_backend_<name>` must match `ADDITIONAL_BACKEND_<name>`
