### ISSUE TITLE
Docs incorrect? How to allow lb to talk to docker?

### ISSUE THREAD

**Issue by howardjones** [docker/dockercloud-haproxy#147]
I'm using docker-compose on my windows desktop against a single vmware-based docker host. From the dockercloud-haproxy docs, I have this for the lb service in my docker-compose.yml:

        volumes:
          - /var/run/docker.sock:/var/run/docker.sock

And I get this error:

    ERROR: for lb  Cannot create container for service lb: b'create \\var\\run\\docker.sock: "\\\\var\\\\run\\\\docker.sock" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed'

If I *don't* have the volume to expose the socket to the lb container, then the lb starts, says it can't talk to docker and just sits there.

Is there something else I need? Like a global volumes: entry?

**Comment by howardjones** [comment]
Actually - I just noticed that those are backslashes in the error message. Is this some strange python thing translating paths when it shouldn't?

**Comment by tifayuki** [comment]
I think the err msg is from docker-compose. Looks like it first translates `/` to `\` and than tries to escape `\` with `\\`.
