### ISSUE TITLE
In swarm mode, want to lb listen port 80 to backend with servers:80 and listen:443 to backend with servers:443 

### ISSUE THREAD

**Issue by lhenry7** [docker/dockercloud-haproxy#148]
Service has  --env "SERVICE_PORTS=80,443" \
                    --env "VIRTUAL_HOST=http://myapp.com,https://myapp.com" 

haproxy has frontend bind:80 and frontend bind:443, with one backend with servers, both port 80 and 443:
backend SERVICE_myapp
  server myapp.1.6fioqzisqprvnh52qh0yal6bk 10.0.0.5:80 check inter 2000 rise 2 fall 3
  server myapp.2.c5le3ophqhx4va77i1ryztzcj 10.0.0.5:443 check inter 2000 rise 2 fall 3

Both frontends use the same backend SERVICE_myapp. How can I have listen:80 use backend with only server:80 and listen:443 use backend with only servers:443 ?

**Comment by tifayuki** [comment]
@lhenry7 

`dockercloud/haproxy` assumes that there is only one service running in a container. As a result, you are expected only using one port on each container for load balance. As to your issue, here is one workaround:
using one port for http load balancing, and the other one using tcp load balancing. 
For example you can set `--env "SERVICE_PORTS=80,443" --env "VIRTUAL_HOST=https://myapp.com" --env "TCP_PORTS=80"`
