### ISSUE TITLE
Adding external backends

### ISSUE THREAD

**Issue by crazyfrozenpenguin** [docker/dockercloud-haproxy#162]
I'm trying to run the following scenario in OSX using Docker native (no docker-machine).

1. In my system (out of docker) I run a web server to listen in external IP and port 8080.
2. In Docker I run another web server and haproxy using:

```docker-compose
version: "2"

services:

  web:
    image: web:latest
    ports:
      - "8081"

web-lb:
    image: dockercloud/haproxy:1.6.2
    ports:
      - 80:80
    depends_on:
      - web
    links:
      - web
    environment:
      - "ADDITIONAL_BACKENDS_EXWEB=backend default_service, server exweb external.ip:8080 check inter 2000 rise 2 fall 3"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```

Notes:
. I've confirmed that my haproxy container can connect to my external.ip address

. I've tried many different combinations for ADDITIONAL_BACKENDS:

 - ADDITIONAL_BACKENDS_EXWEB=backend default_service, server exweb external.ip:8080 check inter 2000 rise 2 fall 3
- ADDITIONAL_BACKENDS_EXWEB=backend other, server exweb external.ip:8080 check inter 2000 rise 2 fall 3
 - ADDITIONAL_BACKENDS_EXWEB=server exweb external.ip:8080 check inter 2000 rise 2 fall 3

And the same without: "_EXWEB"

- ADDITIONAL_BACKENDS=backend default_service, server exweb external.ip:8080 check inter 2000 rise 2 fall 3
- ADDITIONAL_BACKENDS=backend other, server exweb external.ip:8080 check inter 2000 rise 2 fall 3
 - ADDITIONAL_BACKENDS=server exweb external.ip:8080 check inter 2000 rise 2 fall 3

I'm sure I'm missing something, and help would be appreciated. This is to be used in the next few days in an AWS deployment. Any ideas?

**Comment by lnogol** [comment]
try `ADDITIONAL_BACKEND_EXWEB=server exweb external.ip:8080 check inter 2000 rise 2 fall 3`

**Comment by tifayuki** [comment]
@crazyfrozenpenguin 

Other than the backend, you also need to add a related frontend.
However, the evvar `EXTRA_FRONTEND_SETTINGS_<PORT>` only adds setting to an existing frontend. The current implementation of the script doesn't create a new frontend, if there is no frontend listening to that port.

**Comment by dev-lusaja** [comment]
Hi,
im have a code example for this question in docker-compose version 1 and 2.

https://github.com/dev-lusaja/Docker-Cloud-HAproxy

I hope this is useful
