### ISSUE TITLE
Provide release notes

### ISSUE THREAD

**Issue by Levino** [docker/dockercloud-haproxy#164]
Please provide release notes for every release.

For example: Why is there 1.5.3 and then 1.6.0? I assume there are no breaking changes but what are the interface extensions that required the minor to be bumped? Where some bugfixes also applied? Should I update from 1.5.3 to 1.6.3 or am I fine with 1.5.3? I am happy with 1.5.3 but maybe missing out on some bugfixes. Right now I have to go through all commits to find out...

**Comment by tifayuki** [comment]
@Levino 
1.6.0 supports swarm mode, that is why the minor version is bumped.

The release information can be found here: https://github.com/docker/dockercloud-haproxy/releases

**Comment by Levino** [comment]
Sorry about that. I thought I checked the releases. Never mind then, my bad. Thanks for referencing!
