### ISSUE TITLE
Configure as a SNI proxy

### ISSUE THREAD

**Issue by 0x4139** [docker/dockercloud-haproxy#165]
I have the following usecase:
- application A with it's own trusted SSL running on a.com
- application b with it's own trusted SSL running on b.com

i want to configure the haproxy so i can use a SNI proxy. i have no clue how to do this with this current configuration

**Comment by tifayuki** [comment]
@0x4139 
Simply put all your SSL certificates to the haproxy container, and haproxy will handle SNI itself.

See: https://github.com/docker/dockercloud-haproxy#ssl-termination

**Comment by 0x4139** [comment]
i don't want haproxy to handle the certificates i just want to handle the SNI.
- haproxy should look into the host of the handshake and forward the request to the apropiate service

**Comment by tifayuki** [comment]
I think you are talking about reverse proxy using SNI with SSL passthrough.

This can be config in the TCP mode in haproxy, see discussion here: http://serverfault.com/questions/625362/can-a-reverse-proxy-use-sni-with-ssl-pass-through

However, we don't support it directly. You can give a try to see if it can be configured using some envvars like `EXTRA_XXX_SETTINGS` mentioned in the README manually, but personally I don't think it is going to work well.

And a PR is always welcomed.
Thank you.
