### ISSUE TITLE
Periodically haproxy returns 401 Unauthorized with a realm of "Haproxy statistics"

### ISSUE THREAD

**Issue by srevenant** [docker/dockercloud-haproxy#168]
Running in Docker Cloud, clustered against a simple application, if I loop curl calls to the application every ~5 or so returns a 401 Unauthorized:

< HTTP/1.1 401 Unauthorized
< Date: Tue, 21 Feb 2017 18:58:52 GMT
< Content-Type: text/html
< Transfer-Encoding: chunked
< Connection: keep-alive
< Cache-Control: no-cache
< WWW-Authenticate: Basic realm="Haproxy Statistics"

I cannot figure out why it would be doing this.  It seems that haproxy has decided something is calling the statistics path.

It seems to only be happening on the second haproxy (I have scaled it to two proxies).  Even if I redeploy the second haproxy, it does this.

**Comment by srevenant** [comment]
I have verified, it appears this problem only happens when I scale the haproxy service in Docker Cloud to more than one node.

**Comment by tifayuki** [comment]
@srevenant 
Did you select `SEQUENTIAL DEPLOYMENT` when deploying the haproxy service?
