### ISSUE TITLE
haproxy not adding new services to backend

### ISSUE THREAD

**Issue by kulkaamb** [docker/dockercloud-haproxy#17]
I'm trying to deploy following YAML to a UCP Swarm Cluster
version: '2'
services:
  web:
    image: dockercloud/hello-world
  lb:
    image: dockercloud/haproxy
    links:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80

When I do a docker-compose scale web=2, nothing happens inside the HA Proxy. Its still just pointing the be original container and container 2 never gets added.

Here is more info 
1. Docker UCP/SWARM info
docker info
Containers: 32
 Running: 31
 Paused: 0
 Stopped: 1
Images: 66
Server Version: swarm/1.1.3
Role: primary
Strategy: spread
Filters: health, port, dependency, affinity, constraint
Nodes: 6

2. Inside the HA Proxy Container, cat /haproxy.cfg shows

frontend default_frontend
  bind :80
  maxconn 4096
  default_backend default_service
backend default_service
  server dockercloudhaproxy_web_1 dockercloudhaproxy_web_1:80 check

When 2nd container is launched with docker-compose scale web=2, I woudl expect a dockercloudhaproxy_web_2 added to the default_service.

Am I missing anything? What else can I do to troubleshoot?

**Comment by tifayuki** [comment]
Not sure, but I think the problem is that you mount `docker.sock`, and `dockercloud/haproxy` only reloads when the web containers is scheduled to that node.

Can you try to use the following settings, where docker host is the swarm api:
```
    environment:
      - DOCKER_TLS_VERIFY
      - DOCKER_HOST
      - DOCKER_CERT_PATH
    volumes:
      - $DOCKER_CERT_PATH:$DOCKER_CERT_PATH
```

**Comment by kklepper** [comment]
I don't know about docker-compose version 2, haproxy seems to have problems with it. 

In version 1 you must use `force-recreate` as a parameter, like so:

    docker-compose scale web=5 && \
    docker-compose up --force-recreate -d && \
    sudo docker-compose ps

You can see the state like so:

    sudo docker exec -it YOUR-PROJECT-NAME_lb_1 bash -c 'cat /haproxy.cfg'

Works perfectly except for the recreate process, which is obviously only needed for lb and takes quite some time, but cannot be restricted to it as far as I found out.

**Comment by kklepper** [comment]
To be complete: You can see the state of haproxy with 

    docker-compose logs

as well (with information about all the other containers).

**Comment by mklatsky** [comment]
What I have seen is that haproxy will add the number of servers/2 +1. For example, if I do 
docker-compose scale web=10, haproxy will see 6 of them. If I scale to 11, there will be no change. If I then scale to 12, haproxy will see 7 servers.

**Comment by tifayuki** [comment]
@mklatsky 
Are you using swarm?  I guess this could happen if you have a two nodes swarm cluster and you set the DOCKER_HOST as one of the node(or mounting docker.sock in Linux). In such a case, `dockercloud/haproxy` can only read containers on that node. 

I think when using swarm, you have to run `dockercloud/haproxy` as follows, where DOCKER_HOST is the one of the swarm, not the one of a specific docker host:
```
    environment:
      - DOCKER_TLS_VERIFY
      - DOCKER_HOST
      - DOCKER_CERT_PATH
    volumes:
      - $DOCKER_CERT_PATH:$DOCKER_CERT_PATH
```
