### ISSUE TITLE
EXCLUDE_PORTS require a HAproxy redeploy

### ISSUE THREAD

**Issue by jcrombez** [docker/dockercloud-haproxy#18]
My ```webdevops/php-apache``` container expose ```80```, ```443``` and ```9000```.

First, I only set ```VIRTUAL_HOST```, so i ended up with 3 backends, but only ```80``` is supposed to work in my case.

So then, as the documentation says, i added ```EXCLUDE_PORTS=443,9000``` but after a redeploy of the web container, HAproxy kept the 3 backends.

I had to redeploy HAproxy in order to apply the ```EXCLUDE_PORTS``` configuration.

I guess it's not the expected behavior =)

**Comment by tifayuki** [comment]
I tested it in dockercloud, but cannot reproduce the issue. Did you set the global role on the dockercloud/haproxy container?

**Comment by jcrombez** [comment]
No i didn't, the documentaiton says it's only if the proxy is part of a stack or created with docker-cloud cli. Mine is a simple service.

**Comment by tifayuki** [comment]
You have to set `roles` to `global` as shown in: https://github.com/docker/dockercloud-haproxy#running-in-docker-cloud

Otherwise `dockercloud/haproxy` will not detect the changes on the linked services.

**Comment by jcrombez** [comment]
The doc says :

```
If you are using docker-cloud cli, or stackfile, please set roles to global
```

What i understand if that if not using stackfile or cli, no need for global role.

So i must create a HAproxy with a stackfile ?

**Comment by tifayuki** [comment]
If you simply launch a service on the webUI, you need to give `Full access` to `API roles`:
<img width="1088" alt="screen shot 2016-03-28 at 1 59 40 pm" src="https://cloud.githubusercontent.com/assets/5781551/14077606/7ab98cfc-f4ed-11e5-9e66-3bbdd48ad610.png">

**Comment by jcrombez** [comment]
Oh, sorry, i missed that part.
Thank you... sorry for this false issue.
