### ISSUE TITLE
How to use stick-tabels to get session stickiness

### ISSUE THREAD

**Issue by Franklin89** [docker/dockercloud-haproxy#187]
It would be nice to see an examle using stick-tables for session stickiness.

Since of version 1.6 appsession was removed. So that could also be removed from the documentation and instead add some documentation about stick-tables.

**Comment by tifayuki** [comment]
@Franklin89 
I have removed appsession in staging branch and create a new issue to support stick-table: https://github.com/docker/dockercloud-haproxy/issues/191
Close this one.
