### ISSUE TITLE
503 Service Unavailable

### ISSUE THREAD

**Issue by getvivekv** [docker/dockercloud-haproxy#188]
Here is the weird issue that I am facing.  I have over 30+ container and all are accessible through the virtual host except one.  When I access the domain I see this error message.

```
503 Service Unavailable
No server is available to handle this request.
```

Here is what my troubleshooting effort but I am not finding what is the issue. 

The domain that I am trying to access is 

vvasukut-pl.mydomain.net 

```
 / # cat haproxy.cfg | grep vvasukut
   acl host_rule_21 hdr_reg(host) -i ^.*vvasukut-pl\.mydomain\.net$
   acl host_rule_21_port hdr_reg(host) -i ^.*vvasukut-pl\.mydomain\.net:80$
   use_backend SERVICE_vvasukut-pl if host_rule_21 or host_rule_21_port
   acl host_rule_24 hdr_reg(host) -i ^.*vvasukut-sl\.mydomain\.net$
   acl host_rule_24_port hdr_reg(host) -i ^.*vvasukut-sl\.mydomain\.net:80$
  use_backend SERVICE_vvasukut-sl if host_rule_24 or host_rule_24_port
 backend SERVICE_vvasukut-pl
   server vvasukut-pl.1.5pwggqaikiza0thzcka4wssul 10.0.0.35:80 check inter 2000 rise 2 fall 3
 backend SERVICE_vvasukut-sl
  server vvasukut-sl.1.9wibh940fv28s64hsntvfxq5j 10.0.0.51:80 check inter 2000 rise 2 fall 3
/ # 

```

As per the haproxy.cfg, the container is having an IP address 10.0.0.35:80
Haproxy is successfully configured automatically as far as I can see. However if I am trying to access the IP address from within the haproxy container, I can't connect to the container.

> / # wget 10.0.0.35:80 
> Connecting to 10.0.0.35:80 (10.0.0.35:80)
> wget: can't connect to remote host (10.0.0.35): Operation timed out
> 

I also made sure that apache is running on 10.0.0.35:80.

Whereas, I have another container 10.0.0.51:80  with a domain name vvasukut-sl.mydomain.net is successfully loading and here is the wget result from within the container 

> / # wget 10.0.0.51:80 
> Connecting to 10.0.0.51:80 (10.0.0.51:80)
> wget: server returned error: HTTP/1.1 500 Internal Server Error
> / # 

You can ignore the 500 response as it is expected. However for the first container I am getting an operation timeout.

I tried to terminate the docker service and recreated it. Everytime I used the same command to recreate it and it didn't work. 

The following is the command that I used to create the service. 

> docker service create --name vvasukut-pl --network proxy --mount type=bind,source=/mnt/efs/dev/vvasukut/authorized_keys,target=/root/.ssh/authorized_keys,readonly=false --mount type=bind,source=/mnt/efs/private-label/share/,target=/pl/share,readonly=false --mount type=volume,source=vvasukut-pl-58ec400d42a4e,target=/pl,readonly=false --constraint "node.role!=manager"  --env developer=vvasukut --env MYSQL_PASSWORD=vvasukut58e3eed668f9e --env MYSQL_USERNAME=vvasukut-pl --user root -e SERVICE_PORTS="80" --env VIRTUAL_HOST=*vvasukut-pl.mydomain.net --publish 22604:22 --with-registry-auth --limit-memory 1500M --label com.df.notify=true --label com.df.distribute=true  --label com.df.servicePath=/ --label com.df.serviceDomain=*vvasukut-pl.mydomain.net --label com.df.port=80  --label virtualhost=vvasukut-pl.mydomain.net --label volumeName=vvasukut-pl-58ec400d42a4e --label sshport=22604 el:developer

In addition to this, I've deleted this docker service and started another docker service which got this IP 10.0.0.35 automatically. Then I've re-created the above service which got another IP 10.0.0.65. The first one is still not working, but the second one works. 
So it looks like the problem is that the haproxy container is not able to access 10.0.0.35 IP address regardless of the container image.

I am unable to identify if this is a docker network issue or docker proxy issue. Any idea how to troubleshoot further to confirm this bug?

**Comment by getvivekv** [comment]
`docker service inspect vvasukut-pl`
this shows me 
```

"VirtualIPs": [
                {
                    "NetworkID": "5pftkoze5ghfzljtvbz4czuj1",
                    "Addr": "10.255.0.38/16"
                },
                {
                    "NetworkID": "a1m7wxbyxhe9wsfh6u00c5yax",
                    "Addr": "10.0.0.34/24"
                }
            ]
        },

```
However, haproxy detects the IP address of this instance as 10.0.0.35.

Any idea why would haproxy detects a wrong ip address

**Comment by getvivekv** [comment]
I logged into the container and it shows 10.0.0.35 as the IP 

```
root@f2d60ae963c2:~# ifconfig
-bash: ifconfig: command not found
root@f2d60ae963c2:~# ip addr show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
196: eth0@if197: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UP group default 
    link/ether 02:42:0a:ff:00:27 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 10.255.0.39/16 scope global eth0
       valid_lft forever preferred_lft forever
    inet 10.255.0.38/32 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:aff:feff:27/64 scope link 
       valid_lft forever preferred_lft forever
198: eth1@if199: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 02:42:ac:12:00:0e brd ff:ff:ff:ff:ff:ff link-netnsid 1
    inet 172.18.0.14/16 scope global eth1
       valid_lft forever preferred_lft forever
    inet6 fe80::42:acff:fe12:e/64 scope link 
       valid_lft forever preferred_lft forever
200: eth2@if201: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UP group default 
    link/ether 02:42:0a:00:00:23 brd ff:ff:ff:ff:ff:ff link-netnsid 2
    inet 10.0.0.35/24 scope global eth2
       valid_lft forever preferred_lft forever
    inet 10.0.0.34/32 scope global eth2
       valid_lft forever preferred_lft forever
    inet6 fe80::42:aff:fe00:23/64 scope link 
       valid_lft forever preferred_lft forever
root@f2d60ae963c2:~# 

```

**Comment by tifayuki** [comment]
@getvivekv 

Haproxy returns 503 when there is no backend server available to the request. In your case, if haproxy container cannot access `10.0.0.35:80`, the health check marks the server with down status and returns 503.

I am not sure how to troubleshoot the network issue. Maybe it is better to open an issue on docker repo.

**Comment by HonzaMac** [comment]
I've same problem, it shows, that I have on webserver set hostname to `localhost` and server reject any request, which were not from localhost ip range. When I replaced `'localhost'` to `''`, it start to work, because server have fallback to ips, when no host specified. (package amphp/aerys)

**Comment by getvivekv** [comment]
Are you saying that you have modified the apache configuration in the container?

**Comment by HonzaMac** [comment]
I'm using webserver written in php [amphp/aerys](https://github.com/amphp/aerys/). But yes, that means, that I've changed configuration inside container to be less strict about incoming requests.
