### ISSUE TITLE
FORCE_SSL doesn't work

### ISSUE THREAD

**Issue by schickling** [docker/dockercloud-haproxy#19]
It seems like the `FORCE_SSL` param doesn't work. I still can access the `http` endpoints and don't get redirected to `https`.

**Comment by jasonmichels** [comment]
I am having the same issue.  I have DEFAULT_SSL_CERT set and can access my site at both http and https.  I also have FORCE_SSL set to "yes" and VIRTUAL_HOST set to "https://\*", and I can still access both http and https.  I also tried removing FORCE_SSL and VIRTUAL_HOST and it didn't make a difference when running in Docker Cloud.

**Comment by tifayuki** [comment]
To make FORCE_SSL work with VIRTUAL_HOST, you have to set `VIRTUAL_HOST=http://your.domain, https://your.domain`

**Comment by jasonmichels** [comment]
I was finally able to get it to work by setting DEFAULT_SSL_CERT in haproxy, then in the container I was linking too I set FORCE_SSL to "yes" and set the VIRTUAL_HOST as described above.  That specific combination allows the http to https redirect to work.
