### ISSUE TITLE
LetsEncrypt HaProxy Integration

### ISSUE THREAD

**Issue by anton-dealmeida** [docker/dockercloud-haproxy#190]
I have a suggestion,

I have been thinking, what about we add the ability for this container to generate LetsEncrypt certificates generically inside of this container and renew it on the go?

LetsEncrypt will be awesome inside of this container and being able to generate the SSL certs that HAProxy uses for a multi tenant and multi host environment would be incredible useful!

Any opinions?

**Comment by tifayuki** [comment]
@anton-dealmeida 

I agree that this feature is useful and convenient to a lot of users, but I don't think will implement this directly in this repo. I think it is better to keep this project focusing on management of haproxy configuration, and make features like certificate management in somewhere else.

**Comment by Levino** [comment]
I built this: https://github.com/Levino/letsencrypt-cert-service

Works quite okay for me. It could probably use the docker cloud api to overwrite the environment variables of the haproxy.
