### ISSUE TITLE
Could I use this image in Docker for AWS scenery?

### ISSUE THREAD

**Issue by alexsandro-xpt** [docker/dockercloud-haproxy#197]
I would like start some containers services and public all of then at 80 HTTP port each domain/DNS host, all it in AWS, this image is for that?

**Comment by tifayuki** [comment]
@alexsandro-xpt 
Yes, you can use this image in "swarm mode" as described here: https://github.com/docker/dockercloud-haproxy#running-with-docker-swarmmode-swarm-mode
