### ISSUE TITLE
Stats via HTTPS

### ISSUE THREAD

**Issue by butterkekstorte** [docker/dockercloud-haproxy#22]
Hi, is it implemented/possible to have stats served via HTTPS? Maybe I just overlooked, but I cannot find it in the readme.

If it's not implemented, would it be possible?

Thanks!

**Comment by tifayuki** [comment]
you can use EXTRA_BIND_SETTINGS to set `ssl cert /certs/` and set the certificate using `DEFAULT_SSL_CERT`

**Comment by butterkekstorte** [comment]
Hi, no, this does not work.
My regular HTTPS traffic works, but the stats are still not deliver stats via HTTPS.

Any other things i can try?

**Comment by tifayuki** [comment]
I tested the following envvar setting works `-e "EXTRA_BIND_SETTINGS=1936:ssl crt /certs/"`

**Comment by butterkekstorte** [comment]
Works like a charm!
I would suggest to add it to the readme, as it might be of interest to others as well.
