### ISSUE TITLE
[QUESTION] Does this haproxy image defeats the purpose of a service registry?

### ISSUE THREAD

**Issue by odarbelaeze** [docker/dockercloud-haproxy#223]
I'm trying to get more into micro-service architecture, discovering and using this image has made my life easier, the virtual host setup makes it super easy to have any amount of services running under this load balancer's rule. However I was watching this [video](https://www.youtube.com/watch?v=nrzLdMWTRMM) from pycon this year where they split a toy flask application into micro-services, the presenter makes it clear that besides the load balancer one needs a service registry to feed the load balancer. However with haproxy the load balancer is feed out of docker itself, so:
- Does `dockercloud-haproxy` defeat the purpose of setting up a service registry?
- Does it combine a load balancer and a service registry?
- Does it use docker as a service registry?

**Comment by LoungeFlyZ** [comment]
In docker clouds case it is the service registry. You define your services etc.. in your stacks etc... and haproxy feeds of that configuration.  At least thats the way I view it :)

**Comment by odarbelaeze** [comment]
Thanks @LoungeFlyZ
