### ISSUE TITLE
Add option for IP blocking

### ISSUE THREAD

**Issue by ryanshawty** [docker/dockercloud-haproxy#26]
Can't modify the frontend block so can't block any IP addresses, is it possible to had an environment variable for that?

**Comment by tifayuki** [comment]
There is no way to add instructions to the frontend sections. I may add an envvar named `EXTRA_FRONTEND_SETTINGS` to solve it.

**Comment by ryanshawty** [comment]
@tifayuki that would be useful, thanks

**Comment by tifayuki** [comment]
You can do this now in version 1.4 using `EXTRA_FRONTEND_SETTINGS_<PORT>` environment variables.
