### ISSUE TITLE
VIRTUAL_HOST_WEIGHT does not provide a fail over for 503

### ISSUE THREAD

**Issue by modius** [docker/dockercloud-haproxy#27]
I'm trying to set up a maintenance page or fall back for when HAPROXY generates a 503.  This is the error that appears if the service is unreachable, and is seen all too often during service restarts and the like.

I thought using `VIRTUAL_HOST_WEIGHT` would provide a natural failover option, consider:
```
App1:
VIRTUAL_HOST_WEIGHT=1
VIRTUAL_HOST=app1.example.com

App2:
VIRTUAL_HOST_WEIGHT=1
VIRTUAL_HOST=app2.example.com

Common:
VIRTUAL_HOST_WEIGHT=-1
VIRTUAL_HOST=*.example.com
```

So if either `App1` or `App2` fails and generates a 503 you would hope that `Common` would still serve its maintenance/fallback page -- but it doesn't. If I STOP the `App1` service I just start serving a 503 on `app1.example.com` until such time as its restarted. `Common` never kicks in.

Is this entirely expected behaviour, and if so, what can we do to set a failover page that shows something other than the standard 503?

**Comment by tifayuki** [comment]
The `VIRTUAL_HOST_WEIGHT`merely has something to do with the order of HAProxy's ACL rules, which works very similar to the routing rules in IP table. Once a rule is hit, HAProxy always forward the request to the related backends. HAProxy doesn't check the response of the request and try another rules.

In your case, your last `*.example.com` container functions more like a response to 404, not 503.

To handle 503, you may need to check `error file` and `errorloc` here: https://cbonte.github.io/haproxy-dconv/configuration-1.5.html#4.2-errorfile

**Comment by modius** [comment]
Many thanks @tifayuki that makes a lot of sense.  I'll take a look at `errorloc`.

**Comment by modius** [comment]
@tifayuki can't see where I would configure `errorloc` as an environment variable for `dockercloud/haproxy`.

Am guessing that `EXTRA_SETTINGS` is the right environment variable to be putting this into, but can't seem to get the following to work:

```
EXTRA_SETTINGS=errorloc503 503 http://mysite.com/503.html
```

Am I on the right track?

**Comment by tifayuki** [comment]
Yes, setting `EXTRA_SETTINGS=errorloc303 503 http://mysite.com/503.html` will work.

There is no `errorloc503`, but `errorloc302` and `errorloc303`
