### ISSUE TITLE
CPU pegged, repeatedly outputting "INFO:haproxy:Websocket close"

### ISSUE THREAD

**Issue by evanp** [docker/dockercloud-haproxy#29]
I'm using this image to load-balance some microservices on the Docker Cloud. The containers have been dying once every 2-3 hours.

To debug, I did a BYON node, and made sure one of my dockercloud/haproxy instances was deployed to that node. I then used "docker stats" to examine the container. It showed 95% or more CPU utilization on an idle container (not handling any traffic).

When I run "docker logs" on the container, it continuously dumps out "INFO:haproxy:Websocket close".

It seems like the Websocket connection to the Docker Cloud API is cycling really, really quickly.

Example snippet from docker stack YAML at 

https://gist.github.com/evanp/caf8ca6be500afb762b096a261424707

**Comment by evanp** [comment]
As a side node, my Docker Hub account keeps getting locked for "Too many login attempts." And I think this might be related.

**Comment by fermayo** [comment]
@evanp Did the haproxy container show the 95% CPU load? What was the time that passed between `INFO:haproxy:Websocket close`?

**Comment by evanp** [comment]
Yes, the haproxy container. I used "docker stats" to get the figure.

It was scrolling as fast as it could in the console (through an SSH connection, so probably pretty fast).

HERE'S MY THEORY: I think that the container is using some kind of inherited, transient authentication credentials to log into the docker cloud API.

I think that these credentials are expiring after redeployment. However, I think that the container is ignoring that the credentials have expired and trying to re-connect over and over and over and over.

I'm going to try deploying with explicit Docker Cloud credentials using the DOCKERCLOUD_USER and DOCKERCLOUD_APIKEY environment variables that the python-dockercloud module uses.

At the same time, I'll look into doing something better when credentials expire, and send a PR.

**Comment by evanp** [comment]
Looking at the code, it looks like the library will always use the DOCKERCLOUD_AUTH environment variable passed by the Docker Cloud infrastructure for auth, and ignore the DOCKERCLOUD_USER and DOCKERCLOUD_APIKEY.

Oh, and: I'd love to be testing this, but my account is still locked out of 
I'm not sure I can fix this; it seems to be a problem with the lifetime of the DOCKERCLOUD_AUTH.

**Comment by fermayo** [comment]
The `DOCKERCLOUD_AUTH` token only expires when the container is destroyed in Docker Cloud, not before that. Do you have that container running for troubleshooting?

**Comment by svenmueller** [comment]
We are facing the same issue #33

**Comment by tifayuki** [comment]
This is related to API throttling, and we are keep optimizing it on the server side.
Not really an error of this haproxy image, and I am going to close this issue at the moment.
If you still have such a problem, please contact support@docker
