### ISSUE TITLE
FORCE_SSL doesn't seem to work

### ISSUE THREAD

**Issue by thebigredgeek** [docker/dockercloud-haproxy#38]
If I spawn an HAProxy instance with `FORCE_SSL=true` and SSL_CERT equal to a cert string and I try to access the proxy via HTTP, it doesn't redirect to HTTPS.  I know the SSL cert is properly configured... if I access it via HTTPS the browser indicates a secure connection.  What I want is for ha-proxy to redirect incoming HTTP requests to the HTTPS equivalent URL.  Is FORCE_SSL the right approach?

**Comment by ryanshawty** [comment]
Are you setting `FORCE_SSL=true` on the app (i.e. not HAProxy) ?

**Comment by tifayuki** [comment]
To redirect http to ssl, you have to do the following things at the same time:
1) set ssl certificate
2) set `FORCE_SSL=true` on app container
3) when using `VIRTUAL_HOST`, set both http and https hosts on app container. e.g. `VIRTUAL_HOST=http://your.domain, https://your.domain`
