### ISSUE TITLE
SSL by virtual_host

### ISSUE THREAD

**Issue by Rodrive** [docker/dockercloud-haproxy#41]
Hi,
we are using your haproxy service to redirect all our incoming traffic to the good container thanks to the VIRTUAL_HOST environment var.
This works well in http but i didnt manage to make this work for https.
We have one site which need https. So on the app i set:
- VIRTUAL_HOST=http://mysite.com,https://mysite.com
- FORCE_SSL=True
- SSL_CERT=''Mycerts"

Then this website was accessible by https. The thing was if we tried to reach the other websites by https then the certficate sent was the one of mysite.com

Did i miss something to do something like that?

**Comment by tifayuki** [comment]
If you need SSL on other websites, you need to include the certs for those websites at well. If fact, all the certificates are stored in `/certs` in side the haproxy container. It is up to the haproxy to pick up the correct certificate according to the domain you accessed. You can read more about SNI:(https://en.wikipedia.org/wiki/Server_Name_Indication)

If there is not related certificate provided, haproxy will simply use the first cert in the folder.
Hope this answer helps you.

**Comment by Rodrive** [comment]
Thanks for your quick answer.
So is there a way to disable ssl for some VIRTUAL_HOST? Because the problem is for some virtual_host we dont have a SSL certificate, but haproxy still delivers the first cert which provoke a bad ssl connection and results in bad SEO ranking.

Maybe if we can let the webapp terminate the ssl connection would be better (apache or nginx). So haproxy doesnt handle ssl connections, just redirect them to the backend. This also would be great to use certificates generate with letsencrypt because we could generate or renew them directly on the webapp container without need to redeploy the webapp service.
I tried to do this with tutum haproxy but I didnt succeed either.

**Comment by tifayuki** [comment]
If you don't have a SSL cert for some domain, then you can simple do not add that domain to VIRUTAL_HOST, right? something like, `VIRUTAL_HOST="http://domain1, https://domain1, http://domain2"` where you have certs for `domain1` only.

You can always let your app to terminates ssl certs by using TCP mode.

**Comment by Rodrive** [comment]
Oh you are right. I was using a '*' for VIRTUAL_HOST so for exemple i had in my first webapp
VIRTUAL_HOST='http://domain1.com,https://domain1.com' (with a good SSL_CERT)
and then in my second:
VIRTUAL_HOST='*domain2.com' (without a SSL_CERT)
And this is because of this wildcard that haproxy tried to deliver a ssl cert for my second webapp, isn't it ? If i had simply wrote VIRTUAL_HOST='http://domain2.com' and tried to access it in https, haproxy wouldnt deliver nothing.
