### ISSUE TITLE
Easier linking solution?

### ISSUE THREAD

**Issue by dts** [docker/dockercloud-haproxy#45]
I am having a hard time reliably using the CLI to do linking, as every time I want to add one link, it removes all of the others.  Ideally, I'd like HAProxy to interrogate the Docker Cloud API for any services with a VIRTUAL_HOST environment variable, and link against all of those.  Does anybody have something like this working?

**Comment by tifayuki** [comment]
@dts 

If you use `docker-cloud service set --link xxx service_name` to add links, the commands simply overwrites the existing links with the new ones. To add an additional link, you need to specify `--link old_link1 --link old_link2 --link new_link`.

To make this easier, I was thinking to add a set of command like the env command in cli, namely `docker-cloud service link add/ls/set/rm`

The approach to auto load balancing on services with `VIRTUAL_HOST` defined will not be supported, I think.

**Comment by dts** [comment]
Adding a `docker-cloud service link` command would do nicely.  Any reason why you think the auto load balancing wouldn't be supported?

**Comment by mfornasa** [comment]
Same problem here

**Comment by dts** [comment]
@mfornasa, to solve this problem, I've moved from  to AWS ECS & Kubernetes (depending on the client), which are much more flexible and easy to work with.

**Comment by mfornasa** [comment]
@tifayuki how about:

```
To make this easier, I was thinking to add a set of command like the env command in cli, namely docker-cloud service link add/ls/set/rm
```
There is a ticket for that?

**Comment by tifayuki** [comment]
@mfornasa 

No, I don't think there is a ticket for that. It is possible to implement `docker-cloud service link add/ls/set/rm`. What do you think @fermayo ?
