### ISSUE TITLE
High latency when SSL enabled

### ISSUE THREAD

**Issue by PuKoren** [docker/dockercloud-haproxy#52]
Hello all,

On my new deployment, while http requests are fast, https requests takes up to 10 seconds to load. Then once loaded it is fast for each subsequent request for a while.

It was working fine on the previous deployment on tutum, using an older version (`tutum/haproxy:latest`)

Any clue?

**Comment by tifayuki** [comment]
No. The code of dockercloud/haproxy is pretty much like tutum/haproxy on handling SSL certs. In my tests, the SSL enabled haproxy is generally like 2 or 3 seconds slower than the one without SSL.

**Comment by PuKoren** [comment]
Our issue is that is escalades quickly, when over 100/200 req/sec, it takes more than 10sec to serve a request on SSL.

We tried with tutum/haproxy and there is the same issue.

In short, we face the issue on Docker Cloud, but not on Tutum. Do you have any idea of why this happen?

**Comment by tifayuki** [comment]
Does it happen if you run it locally without Docker cloud?
If yes, there could be the issue of this image.
If not, I would guess it is the overlay network issue

Also, can you monitor the CPU usage of the haproxy process, which could be a performance bottleneck?

**Comment by PuKoren** [comment]
@tifayuki I was thinking about the overlay network too, but when switching to host mode I have the issue #53 

Will dig into it this week or the next week to post some update, thanks

**Comment by PuKoren** [comment]
@tifayuki it seems the issue was that the maxconn was reached and requests were delayed. I'm not 100% sure about it so I will let it live over the weekend and see with the day charge tomorrow and update this issue.

Thanks

**Comment by PuKoren** [comment]
Our CPU is 100% when having high load and using SSL, as it takes a lot of CPU.

We will need to fork the repo and add nbproc support for those use-cases. I close the ticket for now as it is not a bug, but a feature request for nbproc
