### ISSUE TITLE
Using networking mode 'host' makes backend to fail at layer4 (timeout)

### ISSUE THREAD

**Issue by PuKoren** [docker/dockercloud-haproxy#53]
When I switch the service settings for network in Docker Cloud, haproxy lists all the backend correctly in stats but they are all in red, failing with a layer4 timeout. Sometimes they go green for a while and go red again.

**Comment by tifayuki** [comment]
I tried to deploy a hello-world service on one node, and haproxy on another node with host networking mode.  Everything works fine at my side. Can you reproduce the issue?

**Comment by PuKoren** [comment]
Here is my config and results:

Haproxy -> 5 containers on 5 nodes with networking host mode
Gateways -> various containers on the same 5 nodes with networking bridge mode

When haproxy is in host mode:
![host_mode](https://cloud.githubusercontent.com/assets/4202557/15270609/e9eb7d76-1a25-11e6-84d1-29a3660ecb53.jpg)
(Failing containers are changing constantly, sometimes green, yellow, or red)

When haproxy is in bridge mode:
![bridge_mode](https://cloud.githubusercontent.com/assets/4202557/15270615/12e71e38-1a26-11e6-9d18-7cc40d36c608.jpg)

All of this on Docker Cloud. Will try to reproduce it locally now
