### ISSUE TITLE
Is there a way to disable the includeSubDomains when using HSTS

### ISSUE THREAD

**Issue by deguif** [docker/dockercloud-haproxy#56]
I saw that HSTS usage in haproxy is hardcoded to includeSubDomains: https://github.com/docker/dockercloud-haproxy/blob/master/haproxy/helper/backend_helper.py#L120 

Is there a way to override this ?

**Comment by tifayuki** [comment]
Yes, you can use `EXTRA_SETTINGS`envvar instead of setting `HSTS_MAX_AGE`

**Comment by deguif** [comment]
Ok thanks @tifayuki , I will try this.

**Comment by deguif** [comment]
Ok nice @tifayuki , it's now working as I expected it to be working ;)
The issue can be closed.
