### ISSUE TITLE
http2 support

### ISSUE THREAD

**Issue by andrelillvede** [docker/dockercloud-haproxy#6]
Is there any plan on implementing a way to use http2 and still be able to use virtual_hosts? It works when using tcp mode but then I can have only that application listening to port 443.

**Comment by samuelgiles** [comment]
I don't think HTTP2 is implemented in HAProxy just yet? I think I've seen mentioned that it may be implemented in 1.7.

**Comment by tifayuki** [comment]
I don't think HTTP2 will be supported in the very near future.

**Comment by anaibol** [comment]
Hi! Any news about this? I think we would need at least haproxy v1.7 to forward http2 requests.
https://ispire.me/http2-ssl-offloading-with-haproxy-and-nginx/
