### ISSUE TITLE
send-proxy support

### ISSUE THREAD

**Issue by blan4** [docker/dockercloud-haproxy#67]
Hello.
I can't find, do you support PROXY protocol introduced in haproxy-1.5 http://www.haproxy.org/download/1.5/doc/proxy-protocol.txt.
For example, I would like to add `send-proxy` option:
```
server servername localhost:25 check inter 2000 rise 2 fall 3 send-proxy
```
So I'll be able to use this, for example: https://github.com/haraka/Haraka/blob/master/docs/HAProxy.md
Thanks.

**Comment by tifayuki** [comment]
There is not such an env var to set the send-proxy directly. 

Although it looks weird, I think setting HEALTH_CHECK="check inter 2000 rise 2 fall 3 send-proxy" will do the trick.

**Comment by blan4** [comment]
@tifayuki Thanks. This solves my problem. May as well It would be good to add extra options env var.
