### ISSUE TITLE
Different VIRTUAL_HOST to specific container ports

### ISSUE THREAD

**Issue by T4cC0re** [docker/dockercloud-haproxy#68]
Hi,

i have a request.

Let's say I have a container `app1` with ports `443` and `8443`. and I would like to forward to a specific port *on that same container* for a different VIRTUAL_HOST: e.g.:
`https://some.example.com` goes to port `443`
and
`https://another.example.com` goes to port `8443`

Is this at all possible?
If so, is it implemented and I am missing something or is this a feature not yet implemented?

Thanks in advance!

**Comment by tifayuki** [comment]
No,  it is not supported.

dockercloud/haproxy assumes one container has only one port to be load balanced with HTTP/HTTPS. If there are multiple ports exposed in a container, other ports should be either excluded from the load balancer or claimed to be used as a TCP ports.

In your case, you can put two nginx/haproxy containers in front of you app, and then link them to dockercloud/haproxy:

```

                        |------------nginx1-----------|
dockercloud/haproxy ----|                             |--------your app
                        |------------nginx2-----------|

```
