### ISSUE TITLE
default EXTRA_SETTINGS for backends

### ISSUE THREAD

**Issue by T4cC0re** [docker/dockercloud-haproxy#69]
Hi,

it would be nice if I could add an overrideable default for EXTRA_SETTINGS defined in linked nodes.
Because I essentially use the same EXTRA_SETTINGS on all services I link it would make it much easier for management purposes.

Example:
`DEFAULT_EXTRA_SETTINGS=rspidel ^x-powered-by:` configured on `dockercloud-haproxy`
and
`EXTRA_SETTINGS=rspidel ^server:` configures on `app1`
and nothing additional on `app2` and `app3`

The config would yield
```
[...]
backend SERVICE_APP1
    [...]
    rspidel ^server:
backend SERVICE_APP2
    [...]
   rspidel ^x-powered-by:
backend SERVICE_APP3
    [...]
   rspidel ^x-powered-by:
[...]
```

Would that be possible?

Thanks in advance!

**Comment by tifayuki** [comment]
It is possible.

The code should be very similar to `EXTRA_ROUTE_SETTINGS`. PRs are always welcomed.
