### ISSUE TITLE
Add ACME support for "Let's Encrypt"

### ISSUE THREAD

**Issue by johanndt** [docker/dockercloud-haproxy#76]
Has anyone thought of, or done any work on integrating https://letsencrypt.org/ certificate generation into this image?

There appears to be an HAProxy plugin with instructions at https://github.com/janeczku/haproxy-acme-validation-plugin

Maybe we can add some options when starting the container so that it will automatically request and generate a new certificate, and then use it?

This should really help the general security of the internet as a whole too. :-)

Thanks!

**Comment by modius** [comment]
You might find some traction here:
https://github.com/docker/dockercloud-haproxy/issues/7

Several folks got a Lets Encrypt model running. Might be a starting point.

**Comment by johanndt** [comment]
Thanks @modius. I did a search but for some reason didn't see that one. Happy to close this as a dupe.
