### ISSUE TITLE
How to Loadbalance between two IP address

### ISSUE THREAD

**Issue by edroot** [docker/dockercloud-haproxy#85]
Hello guys
How to add ip address in backend string
lb_1    |   server WEB1 172.17.0.2:80 check inter 2000 rise 2 fall 3
lb_1    |   server WEB2 172.17.0.3:80 check inter 2000 rise 2 fall 3
need add service in another host
server WEB3 8.8.8.8:80 check inter 2000 rise 2 fall 3

**Comment by tifayuki** [comment]
@edroot 
You can use `EXTRA_SETTINGS` on the linked containers to add an additional route(e.g. EXTRA_SETTINGS=server abc 1.2.3.4`
