### ISSUE TITLE
Is autoscaling feature in the roadmap

### ISSUE THREAD

**Issue by mwaaas** [docker/dockercloud-haproxy#86]
Autoscalling feature where dockercloud/haproxy can trigger scaling up and scaling down depending on the parameters given. 

Something like this http://alex.cloudware.it/2011/10/simple-auto-scale-with-haproxy.html

**Comment by tifayuki** [comment]
@mwaaas 
I don't think this is going to be supported. The scale up and down should be based on the number of containers in the linked services. 

However, you can analyze the traffic in nginx, and decide if you need to scale up/down the containers in the application service.
