### ISSUE TITLE
SSH reverse proxy to services

### ISSUE THREAD

**Issue by gburgett** [docker/dockercloud-haproxy#9]
I'm loving this haproxy implementation so far.  Solves all my load balancing needs save one.

I'm trying to install Gitlab on my private server and would love to be able to forward ssh connections.  HAProxy has this capability, it seems it would require very little additional templating to get this to work with what you guys have already created.
https://confluence.atlassian.com/bitbucketserver/setting-up-ssh-port-forwarding-776640364.html

For now I'm content exposing Gitlab SSH on another port, which works as long as my services aren't scaling beyond one host machine.  At that point I may come back and try to implement this myself.

**Comment by tifayuki** [comment]
SSH connection is simply a TCP connection. I think you can set `TCP_PORTS=<ssh port number>` on your Gitlab and `dockercloud/haproxy` will configured that port using TCP instead of HTTP.
