### ISSUE TITLE
Configuring SSL Session ID stickyness with Docker Compose

### ISSUE THREAD

**Issue by transentia** [docker/dockercloud-haproxy#90]
As the title suggests, I am using Docker compose. I have a backend service that provides an HTTPS endpoint. I want to be able to scale this with compose. HAProxy seems ideally suited for this task.

However, I am having trouble with the requisite configuration in my docker-compose.yml file.

I am trying to follow the example from http://blog.haproxy.com/2011/07/04/maintain-affinity-based-on-ssl-session-id/.

I am trying to add a configuration equivalent to:

    mode tcp

    # maximum SSL session ID length is 32 bytes.
    stick-table type binary len 32 size 30k expire 30m

    acl clienthello req_ssl_hello_type 1
    acl serverhello rep_ssl_hello_type 2

    # use tcp content accepts to detects ssl client and server hello.
    tcp-request inspect-delay 5s
    tcp-request content accept if clienthello

    # no timeout on response inspect delay by default.
    tcp-response content accept if serverhello

    stick on payload_lv(43,1) if clienthello

    # Learn on response if server hello.
    stick store-response payload_lv(43,1) if serverhello

    option ssl-hello-chk

I THINK that I am almost there but--frustratingly--I cannot find out how to specify the `tcp-response content accept if serverhello` configuration.

Here is where I am currently:

    services:
        lb:
          image: dockercloud/haproxy
          links:
          - webi
          volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          ports:
          - 9014:80
          - 1936:1936
        environment:
            # how to configure this:
            #   tcp-response content accept if serverhello

            EXTRA_FRONTEND_SETTINGS_80: >-
              balance roundrobin,
              stick-table type binary len 32 size 30k expire 30m,
              acl clienthello req_ssl_hello_type 1,
              acl serverhello rep_ssl_hello_type 2,
              tcp-request inspect-delay 5s,
              tcp-request content accept if clienthello,
              stick on payload_lv(43\,1) if clienthello,
              stick store-response payload_lv(43\,1) if serverhello

This seems to get me what I want, the log contains:

    ...
    frontend default_port_80
      bind :80
      reqadd X-Forwarded-Proto:\ http
      maxconn 4096
      balance roundrobin
      stick-table type binary len 32 size 30k expire 30m
      acl clienthello req_ssl_hello_type 1
      acl serverhello rep_ssl_hello_type 2
      tcp-request inspect-delay 5s
      tcp-request content accept if clienthello
      stick on payload_lv(43,1) if clienthello
      stick store-response payload_lv(43,1) if serverhello

      default_backend default_service
    backend default_service
      server swarm_webi_1 swarm_webi_1:9014 check inter 2000 rise 2 fall 3
    ...

If I add the tcp-response stanza to EXTRA_FRONTEND_SETTINGS_80, I get:

    [ALERT] 205/113829 (11) : parsing [/haproxy.cfg:47] : tcp-response content is only allowed in 'backend' sections
    [ALERT] 205/113829 (11) : Error(s) found in configuration file : /haproxy.cfg

I have dug around a bit and found that EXTRA_BACKEND_SETTINGS has recently been added , but specifying:

    EXTRA_BACKEND_SETTINGS: >-
        tcp-response content accept if serverhello

doesn't seem to have any noticable affect, even though I am running a version that should have it(?):

    INFO:haproxy:dockercloud/haproxy 1.5.2 is running outside Docker Cloud

I briefly tried to create a custom image, but didn't make any progress...

I would be grateful for any suggestion regarding how I can get over the line.

**Comment by tifayuki** [comment]
@transentia 

I don't think there is a `EXTRA_BACKEND_SETTINGS` environment variable. 
Instead, you can set the "tcp-response" using `EXTRA_SETTINGS` in the linked container. It should work as expected.

**Comment by transentia** [comment]
Thanks for responding @tifayuki 

I was getting EXTRA_BACKEND_SETTINGS from https://github.com/docker/dockercloud-haproxy/pull/79

Apologies, I am feeling a bit dumb. How do I set "EXTRA_SETTINGS in the linked container"?

Do you mean:

    services:
        lb:
            ...

        other:
          EXTRA_SETTINGS: >-
              tcp-response ...

**Comment by tifayuki** [comment]
@transentia 
Yes.
The #79 is not merged, as it does the same as `EXTRA_SETTINGS` does.
