### ISSUE TITLE
Example Stack File ERR_CONNECTION_TIMED_OUT

### ISSUE THREAD

**Issue by logiXbomb** [docker/dockercloud-haproxy#91]
When using the example stack file I get no response from the service endpoint

I'm deploying to a single AWS node

**Comment by tifayuki** [comment]
@logiXbomb 
That means there is a network issue between you and the haproxy on the node. Can you check your firewall and the security group on you aws node?

**Comment by sunshineo** [comment]
+1
I'm experiencing this simply because my haproxy point to a service that is running on another node.
I swear the second I moved the haproxy to the same node the service is running on this error goes away.

**Comment by logiXbomb** [comment]
Check the security group for your node, inbound needs to be set to TCP:0 - 65535, or whatever ports you are using, having it set to ALL will not work

**Comment by sunshineo** [comment]
@logiXbomb The node is brought up automatically by docker cloud. And what I experience is something very strange. Not all traffic fails, only those js and css files requested by the browser.
